### ISSUE TITLE
Trouble opening OPeNDAP endpoint ending with .ncml

### ISSUE THREAD

**Issue by rsignell-usgs** [Reading-eScience-Centre/edal-java#66]
When I try to add this OPeNDAP Data Endpoint
http://geoport-dev.whoi.edu/thredds/dodsC/clay/usgs/users/zdefne/run076/his/00_dir_roms_display.ncml
in the `Location` field in for a new dataset (called "Barnegat-DAP") in the ncWMS2 admin GUI, I get an Error:
```
Status of dataset Barnegat-DAP (for debugging)

State: ERROR
Loading progress

Starting loading
Using dataset factory: class uk.ac.rdg.resc.edal.dataset.cdm.CdmGridDatasetFactory
Error report

Stack trace:
uk.ac.rdg.resc.edal.exceptions.DataReadingException :Problem reading underlying NetCDF dataset
uk.ac.rdg.resc.edal.dataset.cdm.NetcdfDatasetAggregator.openDataset(NetcdfDatasetAggregator.java:396)
...
```
I'm guessing that that this is because this OPeNDAP endpoint ends in '.ncml', so edal-java is assuming that it is an NcML file instead of an OPeNDAP data endpoint?

This used to be a problem with netcdf-java, but it is not a problem with recent versions.  It opens just fine in ToolsUI, for example:
![2016-08-10_16-27-32](https://cloud.githubusercontent.com/assets/1872600/17569692/63d1c8c6-5f17-11e6-8f7f-5def7dfa3ee5.jpg)

**Comment by guygriffiths** [comment]
OK, thanks for pointing this out.  It's an easy enough fix in itself, but it's highlighting the missing image issue you found here:
https://github.com/Reading-eScience-Centre/edal-java/issues/46#issuecomment-238984611

I'll close this issue once we've done a release, but I'll wait until I've fixed the SGRID/NcML issues first

**Comment by rsignell-usgs** [comment]
Just to clarify, we still have the issue of ncWMS2 thinking that a URL that ends in `.ncml` must be an NcML file, right?    Or at least that an OPeNDAP endpoint with NcML at the end is not being opened as OPeNDAP?

**Comment by guygriffiths** [comment]
No, I've fixed it, certainly in my local copy if not the github develop branch. It'll work in the next release.

**Comment by rsignell-usgs** [comment]
Okay!  Looking forward to next release!
